targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/dto/{{}}.dart': 'lib/dto/mapper/{{}}.g.dart'
            '^lib/repository/{{}}.dart': 'lib/repository/generated/{{}}.g.dart'
